-- MySQL Script generated by MySQL Workbench
-- Sat Jun 27 21:17:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema My-Fis
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `My-Fis` ;

-- -----------------------------------------------------
-- Schema My-Fis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `My-Fis` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `My-Fis` ;

-- -----------------------------------------------------
-- Table `tblAdmin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tblAdmin` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tblAdmin` (
  `AdminID` INT NOT NULL,
  `AdminFirstName` NVARCHAR(30) NULL,
  `AdminLastName` NVARCHAR(20) NULL,
  `AdminIdentityNo` SMALLINT(10) NULL,
  `AdminEmail` NVARCHAR(30) NULL,
  `AdminPassword` NVARCHAR(10) NULL,
  `StatusID` INT NULL,
  PRIMARY KEY (`AdminID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tblPage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tblPage` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tblPage` (
  `PageID` INT NOT NULL,
  `PageTitle` VARCHAR(250) NULL,
  `PageContent` TEXT NULL,
  `PageDateTime` DATETIME NULL,
  `PagePicturePath` NVARCHAR(100) NULL,
  `PageDescription` TEXT NULL,
  `PageKeywords` TEXT NULL,
  `PageStatusID` INT NULL,
  PRIMARY KEY (`PageID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tblPageStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tblPageStatus` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tblPageStatus` (
  `PageStatusID` INT NOT NULL,
  `PageStatusName` NVARCHAR(30) NULL,
  PRIMARY KEY (`PageStatusID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tblSlide`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tblSlide` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tblSlide` (
  `SlideID` INT NOT NULL,
  `SlideTitle` NVARCHAR(100) NULL,
  `SlideUrl` NVARCHAR(100) NULL,
  `SlidePicPath` NVARCHAR(100) NULL,
  PRIMARY KEY (`SlideID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tblStateAgency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tblStateAgency` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tblStateAgency` (
  `StateAgencyID` INT NOT NULL,
  `StateAgencyName` NVARCHAR(30) NULL,
  `StateAgencyNo` BIGINT(10) NULL,
  `StateAgencyEmail` NVARCHAR(30) NULL,
  `StateAgencyPassword` NVARCHAR(10) NULL,
  `StatusID` INT NULL,
  PRIMARY KEY (`StateAgencyID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tblStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tblStatus` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tblStatus` (
  `StatusID` INT NOT NULL,
  `StatusName` NVARCHAR(20) NULL,
  PRIMARY KEY (`StatusID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tblStatusAuth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tblStatusAuth` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tblStatusAuth` (
  `StatusAuthID` INT NOT NULL,
  `StatusAuthName` NVARCHAR(20) NULL,
  `StatusID` INT NULL,
  PRIMARY KEY (`StatusAuthID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tblUser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tblUser` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tblUser` (
  `UserID` INT NOT NULL,
  `UserFirstName` NVARCHAR(30) NULL,
  `UserLastName` NVARCHAR(20) NULL,
  `UserIdentityNo` BIGINT(10) NULL,
  `UserPassword` VARCHAR(10) NULL,
  `UserStatusID` SMALLINT(10) NULL,
  `UserFamilyNo` INT NULL,
  `UserDetailsID` INT NULL,
  `UserLocationsID` INT NULL,
  PRIMARY KEY (`UserID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tblUserDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tblUserDetails` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tblUserDetails` (
  `UserDetailsID` INT NOT NULL,
  `UserAdressCity` NVARCHAR(15) NULL,
  `UserAdressDistrict` NVARCHAR(25) NULL,
  `UserAdressStreet` NVARCHAR(25) NULL,
  `UserAdressNo` NVARCHAR(10) NULL,
  `UserAdressApartmentName` NVARCHAR(20) NULL,
  `UserEmail` NVARCHAR(25) NULL,
  `UserPhone` NVARCHAR(15) NULL,
  `UserFamilyPeopleCount` VARCHAR(45) NULL,
  PRIMARY KEY (`UserDetailsID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tblUserFamily`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tblUserFamily` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tblUserFamily` (
  `UserFamilyID` INT NOT NULL,
  `UserFamilyNo` INT NULL,
  `UserID` INT NULL,
  PRIMARY KEY (`UserFamilyID`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tblUserLocations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tblUserLocations` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tblUserLocations` (
  `UserLocationsID` INT NOT NULL,
  `UserLocationsLat` FLOAT NULL,
  `UserLocationsLon` FLOAT NULL,
  `UserLocationsLastDate` DATETIME NULL,
  PRIMARY KEY (`UserLocationsID`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
